import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Les Gants Mêléciens",
  description: "Generated by create next app", //TODO: update description
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        {children}
      </body>
    </html>
  );
}
