import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";


export const metadata: Metadata = {
  title: "Les Gants Mêléciens",
  description: "Generated by create next app", //TODO: update description
};

// Site en thème clair uniquement : empêche l'assombrissement automatique
// (Samsung Internet, Chrome Android "force dark") qui inversait les couleurs.
export const viewport = {
  colorScheme: "light" as const,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="fr">
        <body>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
